name:                sum-multiples
version:             0.1.0.0
github:              "githubuser/sum-multiples"
license:             BSD3
author:              "Stefano Tondo"
maintainer:          "stondo@egmail.com"
copyright:           "2020 Stefano Tondo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sum-multiples#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sum-multiples-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sum-multiples

tests:
  sum-multiples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sum-multiples
    - hspec
