[package]
name = "sum_even_valued_fibo"
version = "0.1.0"
authors = ["Stefano Tondo <stondo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3" }
